cache:
  directories:
   - $HOME/.m2
language: java
jdk:
 - oraclejdk8
script: 
  - sonar-scanner
 
install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V



